<?php

namespace Table\Quiz\Pytania;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-14 at 22:24:37.
 */
class OdpowiedziTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Odpowiedzi
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Odpowiedzi;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Table\Quiz\Pytania\Odpowiedzi::getInstance
     * @covers \Table\Quiz\Pytania\Odpowiedzi::__construct
     */
    public function testGetInstance() {
        OdpowiedziHelper::resetInstance();

        $quiz = Odpowiedzi::getInstance();

        $this->assertInstanceOf(Odpowiedzi::class, $this->object);
        $this->assertInstanceOf(Odpowiedzi::class, $quiz);

        $this->assertSame($quiz, Odpowiedzi::getInstance());
        $this->assertNotSame($quiz, $this->object);        
    }

}

class OdpowiedziHelper extends Odpowiedzi {
    public static function resetInstance() {
        static::$instance = null;
    }
}