<?php

namespace Row\Quiz\Pytanie;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-14 at 22:24:37.
 */
class OdpowiedzTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Odpowiedz
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = \Table\Quiz\Pytania\Odpowiedzi::getInstance()->find(1)->current();

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    
    /**
     * @covers \Row\Quiz\Pytanie\Odpowiedz::toArray()
     */
    public function testToArray() {
        $array = $this->object->toArray();
        
        $this->assertInternalType('array', $array);
        $this->assertCount(3, $array);
        $this->assertEquals(1, $array['id']);
        $this->assertEquals(1, $array['id_pytania']);
        $this->assertArrayHasKey('tresc', $array);
        $this->assertArrayNotHasKey('wartosc', $array);
    }

    public function testWlasnosci() {
        $this->assertEquals(1, $this->object->id);
        $this->assertEquals(1, $this->object->id_pytania);
        $this->assertEquals(1, $this->object->wartosc);
        $this->assertInternalType('string', $this->object->tresc);
    }
}