<?php

namespace Table\Quiz;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-14 at 22:24:37.
 */
class WynikiTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Wyniki
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Wyniki;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Table\Quiz\Wyniki::getInstance
     * @covers \Table\Quiz\Wyniki::__construct
     */
    public function testGetInstance() {
        WynikiHelper::resetInstance();

        $quiz = Wyniki::getInstance();

        $this->assertInstanceOf(Wyniki::class, $this->object);
        $this->assertInstanceOf(Wyniki::class, $quiz);

        $this->assertSame($quiz, Wyniki::getInstance());
        $this->assertNotSame($quiz, $this->object);        
    }

}

class WynikiHelper extends Wyniki {
    public static function resetInstance() {
        static::$instance = null;
    }
}