<?php

namespace Row;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-14 at 22:24:37.
 */
class QuizTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Quiz
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = \Table\Quiz::getInstance()->find(1)->current();

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    
    /**
     * @covers \Row\Quiz::getPytania()
     */
    public function testGetPytania() {
        $pytania = $this->object->getPytania();
        
        $this->assertCount(3, $pytania);
        $this->assertInstanceOf(\Row\Quiz\Pytanie::class, $pytania[0]);
        $this->assertEquals(1, $pytania[0]->id);
        $this->assertEquals(1, $pytania[0]->id_quizu);
    }

    public function testWlasnosci() {
        $this->assertEquals(1, $this->object->id);
        $this->assertEquals(1, $this->object->aktywny);
        $this->assertEquals('Test', $this->object->nazwa);
    }
}